default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: minesweeper_development

test:
  <<: *default
  database: minesweeper_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
  database: minesweeper_production
  username: minesweeper
  password: <%= ENV["MINESWEEPER_DATABASE_PASSWORD"] %>
